//! GX Toolchain — gx init, gx build, gx install, gx fmt, gx make, gx test

use std::fs;
use std::path::Path;
use std::process::Command;

// ── gx init ───────────────────────────────────────────────────────────────────

pub fn init(name: &str) -> Result<(), String> {
    let dir = Path::new(name);
    if dir.exists() {
        return Err(format!("Directory '{}' already exists", name));
    }

    fs::create_dir_all(dir.join("agents"))
        .and(fs::create_dir_all(dir.join("tests")))
        .map_err(|e| format!("Failed to create directories: {}", e))?;

    // gx.json
    let manifest = format!(
        r#"{{
  "name": "{}",
  "version": "0.1.0",
  "description": "A GX agent project",
  "entry": "main.gx",
  "dependencies": {{
    "js": [],
    "py": [],
    "gx": []
  }}
}}
"#,
        name
    );
    fs::write(dir.join("gx.json"), &manifest)
        .map_err(|e| format!("Failed to write gx.json: {}", e))?;

    // main.gx
    let main_gx = format!(
        r#"// {} — GX project entry point
// Run with: gx run main.gx

agent "{}" {{
  remember {{
    name = "{}"
    started_at = 0
  }}

  when started {{
    memory.started_at = get_timestamp()
    say "Hello from {{memory.name}}! Agent started."
  }}

  brain {{
    plan {{
      plan = {{ action: "idle" }}
    }}

    execute {{
      if plan.action == "idle" {{
        log("{{memory.name}} is ready.")
      }}
    }}

    remember {{
      memory.last_run = get_timestamp()
    }}

    communicate {{
      emit "agent_ready" {{ name: memory.name }}
    }}
  }}
}}
"#,
        name, name, name
    );
    fs::write(dir.join("main.gx"), &main_gx)
        .map_err(|e| format!("Failed to write main.gx: {}", e))?;

    // tests/test_basic.gx
    let test_gx = format!(
        r#"// Basic test for {}
helper "test_basic" {{
  brain {{
    plan {{ plan = {{ action: "test" }} }}
    execute {{
      if plan.action == "test" {{
        result = 1 + 1
        if result == 2 {{
          log("PASS: arithmetic works")
        }} else {{
          log("FAIL: arithmetic broken")
        }}
      }}
    }}
    remember {{ }}
    communicate {{ }}
  }}
}}
"#,
        name
    );
    fs::write(dir.join("tests").join("test_basic.gx"), &test_gx)
        .map_err(|e| format!("Failed to write test: {}", e))?;

    // .gitignore
    fs::write(dir.join(".gitignore"), "dist/\n.gx_cache/\n")
        .map_err(|e| format!("Failed to write .gitignore: {}", e))?;

    println!("Created GX project '{}'", name);
    println!();
    println!("  cd {}", name);
    println!("  gx run main.gx");
    println!();
    println!("Files created:");
    println!("  {}/main.gx        — entry point", name);
    println!("  {}/gx.json        — project manifest", name);
    println!("  {}/agents/        — put your agents here", name);
    println!("  {}/tests/         — test files", name);

    Ok(())
}

// ── gx build ─────────────────────────────────────────────────────────────────

pub fn build(file: &str, output: Option<&str>) -> Result<(), String> {
    if !Path::new(file).exists() {
        return Err(format!("File not found: {}", file));
    }

    // Find the GX binary (ourselves)
    let gx_binary = std::env::current_exe().map_err(|e| format!("Cannot find gx binary: {}", e))?;

    let dist_dir = Path::new("dist");
    fs::create_dir_all(dist_dir).map_err(|e| format!("Cannot create dist/: {}", e))?;

    let stem = Path::new(file)
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("output");

    let out_name = output.unwrap_or(stem);
    let out_path = if cfg!(windows) {
        dist_dir.join(format!("{}.exe", out_name))
    } else {
        dist_dir.join(out_name)
    };

    // Strategy: create a shell script that bundles the gx binary + source
    // For now, create a self-contained launcher script
    let source = fs::read_to_string(file).map_err(|e| format!("Cannot read {}: {}", file, e))?;

    // Embed source via a here-document piped to `gx run -` (stdin mode).
    // This eliminates the TOCTOU race and avoids leaking source in /tmp.
    // The GX runtime supports `gx run -` to read source from stdin.
    let launcher = format!(
        r#"#!/bin/sh
# Self-contained GX program: {}
# Generated by gx build

GX_BINARY="{}"

"$GX_BINARY" run - <<'__GX_SOURCE_EOF__'
{}
__GX_SOURCE_EOF__
"#,
        file,
        gx_binary.display(),
        source
    );

    fs::write(&out_path, &launcher).map_err(|e| format!("Cannot write output: {}", e))?;

    // Make executable on Unix
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(&out_path)
            .map_err(|e| e.to_string())?
            .permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&out_path, perms)
            .map_err(|e| format!("Cannot set permissions: {}", e))?;
    }

    println!("Built: {}", out_path.display());
    println!("Run:   {}", out_path.display());

    Ok(())
}

// ── gx install ────────────────────────────────────────────────────────────────

pub fn install(package: &str) -> Result<(), String> {
    // Parse package: js.axios, py.requests, or bare name
    let (namespace, pkg): (&str, &str) = if let Some(rest) = package.strip_prefix("js.") {
        ("js", rest)
    } else if let Some(rest) = package.strip_prefix("py.") {
        ("py", rest)
    } else if let Some(rest) = package.strip_prefix("rust.") {
        ("rust", rest)
    } else {
        // Try to detect from context or default to js
        ("js", package)
    };

    // Validate package name: only allow letters, digits, hyphens, underscores,
    // dots, slashes (scoped npm packages like @org/pkg), and an optional @version.
    // This blocks shell injection and typosquatting attempts with weird chars.
    let name_valid = pkg
        .bytes()
        .all(|b| b.is_ascii_alphanumeric() || b"@/._-".contains(&b));
    if !name_valid || pkg.is_empty() {
        return Err(format!(
            "Invalid package name '{}'. Only alphanumeric, @, /, ., _, - allowed.",
            pkg
        ));
    }

    match namespace {
        "js" => {
            println!("Installing npm package: {}", pkg);
            let status = Command::new("npm")
                .args(["install", pkg])
                .status()
                .map_err(|_| {
                    "npm not found. Install Node.js from https://nodejs.org".to_string()
                })?;
            if !status.success() {
                return Err(format!("npm install {} failed", pkg));
            }
            update_manifest("js", pkg)?;
            println!("Installed {} (npm)", pkg);
        }
        "py" => {
            println!("Installing Python package: {}", pkg);
            let python =
                find_python().ok_or("Python not found. Install from https://python.org")?;
            let status = Command::new(&python)
                .args(["-m", "pip", "install", pkg])
                .status()
                .map_err(|e| format!("pip failed: {}", e))?;
            if !status.success() {
                return Err(format!("pip install {} failed", pkg));
            }
            update_manifest("py", pkg)?;
            println!("Installed {} (pip)", pkg);
        }
        "rust" => {
            println!(
                "For Rust crate '{}': add to your Cargo.toml and rebuild GX.",
                pkg
            );
            println!("  [dependencies]");
            println!("  {} = \"*\"", pkg);
        }
        _ => return Err(format!("Unknown namespace '{}'", namespace)),
    }

    Ok(())
}

// ── gx fmt ────────────────────────────────────────────────────────────────────

pub fn fmt(file: &str) -> Result<(), String> {
    use crate::indent_parser::is_indent_syntax;
    use crate::lexer::{Lexer, TokenKind};

    let source = fs::read_to_string(file).map_err(|e| format!("Cannot read {}: {}", file, e))?;

    // Progressive syntax: normalize indentation instead of token-based reformatting
    if is_indent_syntax(&source) {
        let formatted = fmt_indent_syntax(&source);
        fs::write(file, &formatted).map_err(|e| format!("Cannot write {}: {}", file, e))?;
        println!("Formatted: {}", file);
        return Ok(());
    }

    let mut lexer = Lexer::new(&source);
    let tokens = lexer
        .tokenize()
        .map_err(|e| format!("Syntax error: {}", e))?;

    let mut output = String::new();
    let mut indent = 0usize;
    let mut last_was_newline = false;

    for token in &tokens {
        match &token.kind {
            TokenKind::Eof => break,
            TokenKind::Newline => {
                if !last_was_newline {
                    output.push('\n');
                    last_was_newline = true;
                }
            }
            TokenKind::LBrace => {
                if !output.ends_with(' ') && !output.ends_with('\n') {
                    output.push(' ');
                }
                output.push('{');
                indent += 1;
                output.push('\n');
                last_was_newline = true;
            }
            TokenKind::RBrace => {
                indent = indent.saturating_sub(1);
                if !last_was_newline {
                    output.push('\n');
                }
                output.push_str(&"    ".repeat(indent));
                output.push('}');
                output.push('\n');
                last_was_newline = true;
            }
            other => {
                if last_was_newline {
                    output.push_str(&"    ".repeat(indent));
                }
                output.push_str(&token_to_str(other));
                output.push(' ');
                last_was_newline = false;
            }
        }
    }

    let formatted = output.trim().to_string() + "\n";
    fs::write(file, &formatted).map_err(|e| format!("Cannot write {}: {}", file, e))?;

    println!("Formatted: {}", file);
    Ok(())
}

fn token_to_str(kind: &crate::lexer::TokenKind) -> String {
    use crate::lexer::TokenKind::*;
    match kind {
        Ident(s) => s.clone(),
        StringLit(s) => format!("\"{}\"", s.replace('"', "\\\"")),
        NumberLit(n) => {
            if n.fract() == 0.0 {
                format!("{}", *n as i64)
            } else {
                format!("{}", n)
            }
        }
        BoolLit(b) => b.to_string(),
        Null => "null".into(),
        Helper => "helper".into(),
        Agent => "agent".into(),
        Brain => "brain".into(),
        Plan => "plan".into(),
        Execute => "execute".into(),
        Remember => "remember".into(),
        Communicate => "communicate".into(),
        Memory => "memory".into(),
        When => "when".into(),
        Started => "started".into(),
        ReRun => "re-run".into(),
        Escalate => "escalate".into(),
        Human => "human".into(),
        Ask => "ask".into(),
        Embed => "embed".into(),
        Infer => "infer".into(),
        Use => "use".into(),
        If => "if".into(),
        Else => "else".into(),
        For => "for".into(),
        Each => "each".into(),
        In => "in".into(),
        Try => "try".into(),
        Catch => "catch".into(),
        Say => "say".into(),
        Log => "log".into(),
        Output => "output".into(),
        Return => "return".into(),
        Emit => "emit".into(),
        Recipe => "recipe".into(),
        Colon => ":".into(),
        Comma => ",".into(),
        Dot => ".".into(),
        Eq => "=".into(),
        EqEq => "==".into(),
        NotEq => "!=".into(),
        Lt => "<".into(),
        LtEq => "<=".into(),
        Gt => ">".into(),
        GtEq => ">=".into(),
        Plus => "+".into(),
        PlusEq => "+=".into(),
        Minus => "-".into(),
        Star => "*".into(),
        Slash => "/".into(),
        Percent => "%".into(),
        LParen => "(".into(),
        RParen => ")".into(),
        LBracket => "[".into(),
        RBracket => "]".into(),
        And => "and".into(),
        Or => "or".into(),
        Not => "not".into(),
        _ => String::new(),
    }
}

// ── gx make ───────────────────────────────────────────────────────────────────

pub fn make(input: &str, out_dir: Option<&str>) -> Result<(), String> {
    use crate::ai;
    use crate::value::Value;
    use std::collections::HashMap;

    // Input is either a .gx spec file or a plain text description
    let spec = if input.ends_with(".gx") && Path::new(input).exists() {
        let raw = fs::read_to_string(input).map_err(|e| format!("Cannot read {}: {}", input, e))?;
        println!("Reading spec: {}", input);
        raw
    } else {
        input.to_string()
    };

    println!("Generating project with AI...");

    let system_prompt = r#"You are an expert software architect and full-stack developer.
Your job is to generate complete, working software projects from specifications.

RULES:
- Return ONLY a valid JSON object — no markdown fences, no explanation, no text before or after
- Every file must contain complete, working code — no placeholder comments like "// TODO" or "// implement me"
- Code must run without modification after following the setup commands
- Prefer simplicity: use the fewest dependencies that get the job done
- Include a helpful README.md in every project

JSON SCHEMA (respond with exactly this structure):
{
  "project_name": "kebab-case-directory-name",
  "description": "one sentence describing what this project does",
  "files": [
    {
      "path": "relative/path/to/file.ext",
      "content": "complete file content as a string"
    }
  ],
  "setup": ["command1", "command2"],
  "run": "command to start the project",
  "notes": "any important notes for the user"
}"#;

    let user_prompt = format!(
        "Generate a complete, working project for the following specification:\n\n{}\n\nReturn only the JSON object.",
        spec.trim()
    );

    let mut params = HashMap::new();
    params.insert("prompt".into(), Value::Str(user_prompt));
    params.insert("system".into(), Value::Str(system_prompt.into()));
    params.insert("max_tokens".into(), Value::Number(4000.0));
    params.insert("temperature".into(), Value::Number(0.2));

    // Try providers in order: openai → anthropic → ollama
    // Use env var GX_PROVIDER to override
    let env_provider = std::env::var("GX_PROVIDER").unwrap_or_default();
    let providers: Vec<(&str, Option<&str>)> = if !env_provider.is_empty() {
        vec![(Box::leak(env_provider.into_boxed_str()), None)]
    } else {
        vec![
            ("openai", Some("gpt-4o-mini")),
            ("anthropic", Some("claude-haiku-4-5")),
            ("ollama", Some("llama3.2:latest")),
        ]
    };
    let mut ai_text = String::new();
    let mut last_error = "No AI provider configured.".to_string();

    for (provider, default_model) in &providers {
        let env_model = std::env::var("GX_MODEL").unwrap_or_default();
        let model = if !env_model.is_empty() {
            Some(env_model.as_str())
        } else {
            *default_model
        };
        let result = ai::ask_ai(provider, model, &params);
        if let Value::Object(ref map) = result {
            if map.get("ok") == Some(&Value::Bool(true)) {
                if let Some(Value::Str(text)) = map.get("text") {
                    ai_text = text.trim().to_string();
                    println!("  (generated with {} {})", provider, model.unwrap_or(""));
                    break;
                }
            } else if let Some(Value::Str(err)) = map.get("error") {
                last_error = err.clone();
            }
        }
    }

    if ai_text.is_empty() {
        return Err(format!(
            "Could not generate project.\n{}\n\nSet OPENAI_API_KEY or ANTHROPIC_API_KEY.",
            last_error
        ));
    }

    // Strip markdown fences the AI sometimes adds despite instructions
    let json_str = strip_json_fences(&ai_text);

    // Parse the JSON response (try raw first, then repair unescaped control chars)
    let json: serde_json::Value = serde_json::from_str(json_str)
        .or_else(|_| {
            let repaired = repair_json(json_str);
            serde_json::from_str(&repaired)
        })
        .map_err(|e| {
            format!(
                "AI returned invalid JSON: {}\n\nRaw response:\n{}",
                e,
                &ai_text[..ai_text.len().min(500)]
            )
        })?;

    let project_name = json["project_name"]
        .as_str()
        .unwrap_or("gx-project")
        .to_string();
    let description = json["description"].as_str().unwrap_or("").to_string();
    let run_cmd = json["run"].as_str().unwrap_or("").to_string();
    let notes = json["notes"].as_str().unwrap_or("").to_string();

    // Determine output directory
    let target_dir = out_dir.unwrap_or(&project_name);
    let target_path = Path::new(target_dir);

    if target_path.exists() {
        return Err(format!(
            "Directory '{}' already exists. Use --out <other-name> to choose a different name.",
            target_dir
        ));
    }

    // Write all files
    let files = json["files"]
        .as_array()
        .ok_or("JSON missing 'files' array")?;
    if files.is_empty() {
        return Err("AI returned no files.".into());
    }

    println!();
    println!("Creating project: {}", target_dir);
    if !description.is_empty() {
        println!("  {}", description);
    }
    println!();

    for file_entry in files {
        let rel_path = file_entry["path"]
            .as_str()
            .ok_or("File entry missing 'path'")?;
        let content = file_entry["content"].as_str().unwrap_or("");

        let full_path = target_path.join(rel_path);

        // Create parent directories
        if let Some(parent) = full_path.parent() {
            fs::create_dir_all(parent)
                .map_err(|e| format!("Cannot create directory {:?}: {}", parent, e))?;
        }

        fs::write(&full_path, content)
            .map_err(|e| format!("Cannot write {:?}: {}", full_path, e))?;

        println!("  wrote  {}/{}", target_dir, rel_path);
    }

    // Setup commands
    let setup_cmds: Vec<String> = json["setup"]
        .as_array()
        .map(|arr| {
            arr.iter()
                .filter_map(|v| v.as_str().map(String::from))
                .collect()
        })
        .unwrap_or_default();

    println!();
    println!("Done! {} file(s) written to {}/", files.len(), target_dir);
    println!();

    if !setup_cmds.is_empty() || !run_cmd.is_empty() {
        println!("Next steps:");
        println!("  cd {}", target_dir);
        for cmd in &setup_cmds {
            println!("  {}", cmd);
        }
        if !run_cmd.is_empty() {
            println!("  {}", run_cmd);
        }
        println!();
    }

    if !notes.is_empty() {
        println!("Notes: {}", notes);
        println!();
    }

    Ok(())
}

/// Escape unescaped control characters inside JSON string values.
/// LLMs often emit literal newlines inside strings instead of \n.
fn repair_json(s: &str) -> String {
    let mut result = String::with_capacity(s.len() + 64);
    let mut in_string = false;
    let mut escaped = false;
    for ch in s.chars() {
        if escaped {
            escaped = false;
            result.push(ch);
            continue;
        }
        if ch == '\\' && in_string {
            escaped = true;
            result.push(ch);
            continue;
        }
        if ch == '"' {
            in_string = !in_string;
            result.push(ch);
            continue;
        }
        if in_string {
            match ch {
                '\n' => result.push_str("\\n"),
                '\r' => result.push_str("\\r"),
                '\t' => result.push_str("\\t"),
                '\x00'..='\x1f' => {
                    result.push_str(&format!("\\u{:04x}", ch as u32));
                }
                _ => result.push(ch),
            }
        } else {
            result.push(ch);
        }
    }
    result
}

fn strip_json_fences(s: &str) -> &str {
    let s = s.trim();
    // Strip ```json ... ``` or ``` ... ```
    if s.starts_with("```") {
        let after_fence = s.trim_start_matches('`');
        // Skip the language identifier if present (e.g. "json\n")
        let after_lang = if let Some(newline) = after_fence.find('\n') {
            &after_fence[newline + 1..]
        } else {
            after_fence
        };
        after_lang
            .trim_end_matches('`')
            .trim_end_matches('\n')
            .trim()
    } else {
        s
    }
}

// ── gx test ───────────────────────────────────────────────────────────────────

pub fn test(path: Option<&str>) -> Result<(), String> {
    use crate::indent_parser::is_indent_syntax;
    use crate::interpreter::Interpreter;
    use crate::lexer::Lexer;
    use crate::parser::Parser;

    let test_dir = path.unwrap_or("tests");

    if !Path::new(test_dir).exists() {
        return Err(format!("Test directory '{}' not found", test_dir));
    }

    let mut test_files = Vec::new();
    collect_gx_files(Path::new(test_dir), &mut test_files);
    test_files.sort();

    if test_files.is_empty() {
        println!("No .gx test files found in '{}'", test_dir);
        return Ok(());
    }

    println!("Running {} test file(s)...\n", test_files.len());

    let mut passed = 0usize;
    let mut failed = 0usize;
    let mut errors = 0usize;
    let mut total_asserts = 0usize;
    let mut failed_asserts: Vec<String> = Vec::new();

    for file in &test_files {
        let source = match fs::read_to_string(file) {
            Ok(s) => s,
            Err(e) => {
                eprintln!("  ERROR  {}: {}", file, e);
                errors += 1;
                continue;
            }
        };

        let program = if is_indent_syntax(&source) {
            match crate::indent_parser::parse(&source) {
                Ok(p) => p,
                Err(e) => {
                    eprintln!("  ERROR  {}: {}", file, e);
                    errors += 1;
                    continue;
                }
            }
        } else {
            let tokens = match Lexer::new(&source).tokenize() {
                Ok(t) => t,
                Err(e) => {
                    eprintln!("  ERROR  {}: {}", file, e);
                    errors += 1;
                    continue;
                }
            };
            match Parser::new(tokens).parse() {
                Ok(p) => p,
                Err(e) => {
                    eprintln!("  ERROR  {}: {}", file, e);
                    errors += 1;
                    continue;
                }
            }
        };

        let mut interp = Interpreter::new();
        interp.base_path = Some(file.to_string());

        match interp.run_program(&program) {
            Ok(_) => {
                total_asserts += interp.assert_count;
                if !interp.assert_failures.is_empty() {
                    for af in &interp.assert_failures {
                        eprintln!("  FAIL   {} — {}", file, af);
                        failed_asserts.push(format!("{}: {}", file, af));
                    }
                    failed += 1;
                } else {
                    let assert_note = if interp.assert_count > 0 {
                        format!(" ({} assertions)", interp.assert_count)
                    } else {
                        String::new()
                    };
                    println!("  PASS   {}{}", file, assert_note);
                    passed += 1;
                }
            }
            Err(e) => {
                total_asserts += interp.assert_count;
                eprintln!("  FAIL   {}: {}", file, e);
                failed += 1;
            }
        }
    }

    println!();
    println!(
        "Results: {} passed, {} failed, {} errors | {} total assertions",
        passed, failed, errors, total_asserts
    );

    if failed > 0 || errors > 0 {
        Err(format!("{} test(s) failed", failed + errors))
    } else {
        Ok(())
    }
}

fn collect_gx_files(dir: &Path, files: &mut Vec<String>) {
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                collect_gx_files(&path, files);
            } else if path.extension().map(|e| e == "gx").unwrap_or(false) {
                if let Some(s) = path.to_str() {
                    files.push(s.to_string());
                }
            }
        }
    }
}

// ── Utilities ─────────────────────────────────────────────────────────────────

fn fmt_indent_syntax(source: &str) -> String {
    // Normalize progressive syntax: standardize indentation to 2 spaces
    let mut result = String::new();
    let mut prev_blank = false;
    for line in source.lines() {
        let trimmed = line.trim_end();
        if trimmed.is_empty() {
            if !prev_blank {
                result.push('\n');
                prev_blank = true;
            }
            continue;
        }
        prev_blank = false;
        // Count existing indentation
        let indent_count = line.len() - line.trim_start().len();
        // Normalize: each 4-space or 1-tab indent level becomes 2 spaces
        let level = if indent_count > 0 {
            indent_count.div_ceil(2)
        } else {
            0
        };
        let indent = "  ".repeat(level);
        result.push_str(&indent);
        result.push_str(trimmed);
        result.push('\n');
    }
    result
}

fn find_python() -> Option<String> {
    for candidate in &["python3", "python"] {
        if Command::new(if cfg!(windows) { "where" } else { "which" })
            .arg(candidate)
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
        {
            return Some((*candidate).into());
        }
    }
    None
}

fn update_manifest(namespace: &str, package: &str) -> Result<(), String> {
    let manifest_path = Path::new("gx.json");
    if !manifest_path.exists() {
        return Ok(());
    }

    let content =
        fs::read_to_string(manifest_path).map_err(|e| format!("Cannot read gx.json: {}", e))?;

    // Simple string replacement — don't want serde_json complexity for this
    let dep_key = format!("\"{}\":", namespace);
    if let Some(pos) = content.find(&dep_key) {
        if let Some(bracket_pos) = content[pos..].find('[') {
            let insert_at = pos + bracket_pos + 1;
            let new_entry = format!("\"{}\"", package);
            // Check if already present
            if content.contains(&new_entry) {
                return Ok(());
            }
            let mut new_content = content.clone();
            new_content.insert_str(insert_at, &format!("{}, ", new_entry));
            fs::write(manifest_path, &new_content)
                .map_err(|e| format!("Cannot write gx.json: {}", e))?;
        }
    }
    Ok(())
}
