//! GX Toolchain — gx init, gx build, gx install, gx fmt, gx make, gx test

use std::fs;
use std::path::Path;
use std::process::Command;

// ── gx init ───────────────────────────────────────────────────────────────────

pub fn init(name: &str) -> Result<(), String> {
    let dir = Path::new(name);
    if dir.exists() {
        return Err(format!("Directory '{}' already exists", name));
    }

    fs::create_dir_all(dir.join("agents"))
        .and(fs::create_dir_all(dir.join("tests")))
        .map_err(|e| format!("Failed to create directories: {}", e))?;

    // gx.json
    let manifest = format!(r#"{{
  "name": "{}",
  "version": "0.1.0",
  "description": "A GX agent project",
  "entry": "main.gx",
  "dependencies": {{
    "js": [],
    "py": [],
    "gx": []
  }}
}}
"#, name);
    fs::write(dir.join("gx.json"), &manifest)
        .map_err(|e| format!("Failed to write gx.json: {}", e))?;

    // main.gx
    let main_gx = format!(r#"// {} — GX project entry point
// Run with: gx run main.gx

agent "{}" {{
  remember {{
    name = "{}"
    started_at = 0
  }}

  when started {{
    memory.started_at = get_timestamp()
    say "Hello from {{memory.name}}! Agent started."
  }}

  brain {{
    plan {{
      plan = {{ action: "idle" }}
    }}

    execute {{
      if plan.action == "idle" {{
        log("{{memory.name}} is ready.")
      }}
    }}

    remember {{
      memory.last_run = get_timestamp()
    }}

    communicate {{
      emit "agent_ready" {{ name: memory.name }}
    }}
  }}
}}
"#, name, name, name);
    fs::write(dir.join("main.gx"), &main_gx)
        .map_err(|e| format!("Failed to write main.gx: {}", e))?;

    // tests/test_basic.gx
    let test_gx = format!(r#"// Basic test for {}
helper "test_basic" {{
  brain {{
    plan {{ plan = {{ action: "test" }} }}
    execute {{
      if plan.action == "test" {{
        result = 1 + 1
        if result == 2 {{
          log("PASS: arithmetic works")
        }} else {{
          log("FAIL: arithmetic broken")
        }}
      }}
    }}
    remember {{ }}
    communicate {{ }}
  }}
}}
"#, name);
    fs::write(dir.join("tests").join("test_basic.gx"), &test_gx)
        .map_err(|e| format!("Failed to write test: {}", e))?;

    // .gitignore
    fs::write(dir.join(".gitignore"), "dist/\n.gx_cache/\n")
        .map_err(|e| format!("Failed to write .gitignore: {}", e))?;

    println!("Created GX project '{}'", name);
    println!();
    println!("  cd {}", name);
    println!("  gx run main.gx");
    println!();
    println!("Files created:");
    println!("  {}/main.gx        — entry point", name);
    println!("  {}/gx.json        — project manifest", name);
    println!("  {}/agents/        — put your agents here", name);
    println!("  {}/tests/         — test files", name);

    Ok(())
}

// ── gx build ─────────────────────────────────────────────────────────────────

pub fn build(file: &str, output: Option<&str>) -> Result<(), String> {
    if !Path::new(file).exists() {
        return Err(format!("File not found: {}", file));
    }

    // Find the GX binary (ourselves)
    let gx_binary = std::env::current_exe()
        .map_err(|e| format!("Cannot find gx binary: {}", e))?;

    let dist_dir = Path::new("dist");
    fs::create_dir_all(dist_dir)
        .map_err(|e| format!("Cannot create dist/: {}", e))?;

    let stem = Path::new(file).file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("output");

    let out_name = output.unwrap_or(stem);
    let out_path = if cfg!(windows) {
        dist_dir.join(format!("{}.exe", out_name))
    } else {
        dist_dir.join(out_name)
    };

    // Strategy: create a shell script that bundles the gx binary + source
    // For now, create a self-contained launcher script
    let source = fs::read_to_string(file)
        .map_err(|e| format!("Cannot read {}: {}", file, e))?;

    // Escape the source for embedding in a shell script
    let escaped = source.replace('\\', "\\\\").replace('\'', "'\\''");

    let launcher = format!(r#"#!/bin/sh
# Self-contained GX program: {}
# Generated by gx build

GX_BINARY="{}"
GX_SOURCE='{}'

# Write source to temp file and run it
TMPFILE=$(mktemp /tmp/gx_XXXXXX.gx)
printf '%s' "$GX_SOURCE" > "$TMPFILE"
"$GX_BINARY" run "$TMPFILE"
STATUS=$?
rm -f "$TMPFILE"
exit $STATUS
"#, file, gx_binary.display(), escaped);

    fs::write(&out_path, &launcher)
        .map_err(|e| format!("Cannot write output: {}", e))?;

    // Make executable on Unix
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(&out_path)
            .map_err(|e| e.to_string())?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&out_path, perms)
            .map_err(|e| format!("Cannot set permissions: {}", e))?;
    }

    println!("Built: {}", out_path.display());
    println!("Run:   {}", out_path.display());

    Ok(())
}

// ── gx install ────────────────────────────────────────────────────────────────

pub fn install(package: &str) -> Result<(), String> {
    // Parse package: js.axios, py.requests, or bare name
    let (namespace, pkg): (&str, &str) = if let Some(rest) = package.strip_prefix("js.") {
        ("js", rest)
    } else if let Some(rest) = package.strip_prefix("py.") {
        ("py", rest)
    } else if let Some(rest) = package.strip_prefix("rust.") {
        ("rust", rest)
    } else {
        // Try to detect from context or default to js
        ("js", package)
    };

    match namespace {
        "js" => {
            println!("Installing npm package: {}", pkg);
            let status = Command::new("npm")
                .args(["install", pkg])
                .status()
                .map_err(|_| "npm not found. Install Node.js from https://nodejs.org".to_string())?;
            if !status.success() {
                return Err(format!("npm install {} failed", pkg));
            }
            update_manifest("js", pkg)?;
            println!("Installed {} (npm)", pkg);
        }
        "py" => {
            println!("Installing Python package: {}", pkg);
            let python = find_python().ok_or("Python not found. Install from https://python.org")?;
            let status = Command::new(&python)
                .args(["-m", "pip", "install", pkg])
                .status()
                .map_err(|e| format!("pip failed: {}", e))?;
            if !status.success() {
                return Err(format!("pip install {} failed", pkg));
            }
            update_manifest("py", pkg)?;
            println!("Installed {} (pip)", pkg);
        }
        "rust" => {
            println!("For Rust crate '{}': add to your Cargo.toml and rebuild GX.", pkg);
            println!("  [dependencies]");
            println!("  {} = \"*\"", pkg);
        }
        _ => return Err(format!("Unknown namespace '{}'", namespace)),
    }

    Ok(())
}

// ── gx fmt ────────────────────────────────────────────────────────────────────

pub fn fmt(file: &str) -> Result<(), String> {
    use crate::lexer::{Lexer, TokenKind};

    let source = fs::read_to_string(file)
        .map_err(|e| format!("Cannot read {}: {}", file, e))?;

    let mut lexer = Lexer::new(&source);
    let tokens = lexer.tokenize()
        .map_err(|e| format!("Syntax error: {}", e))?;

    let mut output = String::new();
    let mut indent = 0usize;
    let mut last_was_newline = false;

    for token in &tokens {
        match &token.kind {
            TokenKind::Eof => break,
            TokenKind::Newline => {
                if !last_was_newline {
                    output.push('\n');
                    last_was_newline = true;
                }
            }
            TokenKind::LBrace => {
                if !output.ends_with(' ') && !output.ends_with('\n') { output.push(' '); }
                output.push('{');
                indent += 1;
                output.push('\n');
                last_was_newline = true;
            }
            TokenKind::RBrace => {
                indent = indent.saturating_sub(1);
                if !last_was_newline { output.push('\n'); }
                output.push_str(&"    ".repeat(indent));
                output.push('}');
                output.push('\n');
                last_was_newline = true;
            }
            other => {
                if last_was_newline {
                    output.push_str(&"    ".repeat(indent));
                }
                output.push_str(&token_to_str(other));
                output.push(' ');
                last_was_newline = false;
            }
        }
    }

    let formatted = output.trim().to_string() + "\n";
    fs::write(file, &formatted)
        .map_err(|e| format!("Cannot write {}: {}", file, e))?;

    println!("Formatted: {}", file);
    Ok(())
}

fn token_to_str(kind: &crate::lexer::TokenKind) -> String {
    use crate::lexer::TokenKind::*;
    match kind {
        Ident(s)     => s.clone(),
        StringLit(s) => format!("\"{}\"", s.replace('"', "\\\"")),
        NumberLit(n) => {
            if n.fract() == 0.0 { format!("{}", *n as i64) }
            else { format!("{}", n) }
        }
        BoolLit(b)   => b.to_string(),
        Null         => "null".into(),
        Helper       => "helper".into(),
        Agent        => "agent".into(),
        Brain        => "brain".into(),
        Plan         => "plan".into(),
        Execute      => "execute".into(),
        Remember     => "remember".into(),
        Communicate  => "communicate".into(),
        Memory       => "memory".into(),
        When         => "when".into(),
        Started      => "started".into(),
        ReRun        => "re-run".into(),
        Escalate     => "escalate".into(),
        Human        => "human".into(),
        Ask          => "ask".into(),
        Embed        => "embed".into(),
        Infer        => "infer".into(),
        Use          => "use".into(),
        If           => "if".into(),
        Else         => "else".into(),
        For          => "for".into(),
        Each         => "each".into(),
        In           => "in".into(),
        Try          => "try".into(),
        Catch        => "catch".into(),
        Say          => "say".into(),
        Log          => "log".into(),
        Output       => "output".into(),
        Return       => "return".into(),
        Emit         => "emit".into(),
        Recipe       => "recipe".into(),
        Colon        => ":".into(),
        Comma        => ",".into(),
        Dot          => ".".into(),
        Eq           => "=".into(),
        EqEq         => "==".into(),
        NotEq        => "!=".into(),
        Lt           => "<".into(),
        LtEq         => "<=".into(),
        Gt           => ">".into(),
        GtEq         => ">=".into(),
        Plus         => "+".into(),
        PlusEq       => "+=".into(),
        Minus        => "-".into(),
        Star         => "*".into(),
        Slash        => "/".into(),
        Percent      => "%".into(),
        LParen       => "(".into(),
        RParen       => ")".into(),
        LBracket     => "[".into(),
        RBracket     => "]".into(),
        And          => "and".into(),
        Or           => "or".into(),
        Not          => "not".into(),
        _            => String::new(),
    }
}

// ── gx make ───────────────────────────────────────────────────────────────────

pub fn make(description: &str, output: Option<&str>) -> Result<(), String> {
    use std::collections::HashMap;
    use crate::ai;
    use crate::value::Value;

    let system_prompt = r#"You are a GX language expert. GX is a brain-first programming language for building transparent AI assistants.

GX SYNTAX:
```
agent "name" {
  remember { key = value }

  when started {
    say "message"
  }

  brain {
    plan {
      if memory.condition { plan = { action: "do_something" } }
    }
    execute {
      if plan.action == "do_something" {
        result = "done"
        memory.result = result
        output("Result: " + result)
      }
    }
    remember {
      memory.last_run = get_timestamp()
    }
    communicate {
      emit "done" { result: memory.result }
    }
  }
}
```

AI primitives: `result = ask openai { prompt: "...", system: "..." }`
The result has: result.text, result.confidence, result.ok

Builtins: log(x), output(x), say x, get_timestamp(), count(x), to_string(x), to_number(x)

Generate ONLY valid GX code. No markdown fences. No explanation."#;

    let user_prompt = format!("Generate a GX agent that does the following: {}", description);

    let mut params = HashMap::new();
    params.insert("prompt".into(), Value::Str(user_prompt));
    params.insert("system".into(), Value::Str(system_prompt.into()));
    params.insert("max_tokens".into(), Value::Number(2000.0));
    params.insert("temperature".into(), Value::Number(0.2));

    // Try providers in order
    let providers = ["openai", "anthropic"];
    let mut last_error = String::new();

    for provider in &providers {
        let result = ai::ask_ai(provider, None, &params);
        if let Value::Object(ref map) = result {
            if map.get("ok") == Some(&Value::Bool(true)) {
                if let Some(Value::Str(code)) = map.get("text") {
                    let code = code.trim().to_string();
                    // Strip markdown fences if AI added them anyway
                    let code = code.trim_start_matches("```gx")
                        .trim_start_matches("```")
                        .trim_end_matches("```")
                        .trim()
                        .to_string();

                    println!("{}", code);

                    if let Some(out_file) = output {
                        fs::write(out_file, &code)
                            .map_err(|e| format!("Cannot write {}: {}", out_file, e))?;
                        println!("\nSaved to: {}", out_file);
                    }

                    return Ok(());
                }
            } else if let Some(Value::Str(err)) = map.get("error") {
                last_error = err.clone();
            }
        }
    }

    Err(format!("Could not generate code. {}\n\nSet OPENAI_API_KEY or ANTHROPIC_API_KEY to use gx make.", last_error))
}

// ── gx test ───────────────────────────────────────────────────────────────────

pub fn test(path: Option<&str>) -> Result<(), String> {
    use crate::lexer::Lexer;
    use crate::parser::Parser;
    use crate::interpreter::Interpreter;

    let test_dir = path.unwrap_or("tests");

    if !Path::new(test_dir).exists() {
        return Err(format!("Test directory '{}' not found", test_dir));
    }

    let mut test_files = Vec::new();
    collect_gx_files(Path::new(test_dir), &mut test_files);

    if test_files.is_empty() {
        println!("No .gx test files found in '{}'", test_dir);
        return Ok(());
    }

    println!("Running {} test file(s)...\n", test_files.len());

    let mut passed = 0usize;
    let mut failed = 0usize;
    let mut errors = 0usize;

    for file in &test_files {
        let source = match fs::read_to_string(file) {
            Ok(s) => s,
            Err(e) => { eprintln!("  ERROR {}: {}", file, e); errors += 1; continue; }
        };

        let tokens = match Lexer::new(&source).tokenize() {
            Ok(t) => t,
            Err(e) => { eprintln!("  ERROR {}: {}", file, e); errors += 1; continue; }
        };

        let program = match Parser::new(tokens).parse() {
            Ok(p) => p,
            Err(e) => { eprintln!("  ERROR {}: {}", file, e); errors += 1; continue; }
        };

        // Capture output to check for PASS/FAIL
        match Interpreter::new().run_program(&program) {
            Ok(_) => { println!("  PASS {}", file); passed += 1; }
            Err(e) => { eprintln!("  FAIL {}: {}", file, e); failed += 1; }
        }
    }

    println!("\n{} passed, {} failed, {} errors", passed, failed, errors);

    if failed > 0 || errors > 0 { Err("Tests failed".into()) } else { Ok(()) }
}

fn collect_gx_files(dir: &Path, files: &mut Vec<String>) {
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                collect_gx_files(&path, files);
            } else if path.extension().map(|e| e == "gx").unwrap_or(false) {
                if let Some(s) = path.to_str() {
                    files.push(s.to_string());
                }
            }
        }
    }
}

// ── Utilities ─────────────────────────────────────────────────────────────────

fn find_python() -> Option<String> {
    for candidate in &["python3", "python"] {
        if Command::new(if cfg!(windows) { "where" } else { "which" })
            .arg(candidate)
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
        {
            return Some((*candidate).into());
        }
    }
    None
}

fn update_manifest(namespace: &str, package: &str) -> Result<(), String> {
    let manifest_path = Path::new("gx.json");
    if !manifest_path.exists() { return Ok(()); }

    let content = fs::read_to_string(manifest_path)
        .map_err(|e| format!("Cannot read gx.json: {}", e))?;

    // Simple string replacement — don't want serde_json complexity for this
    let dep_key = format!("\"{}\":", namespace);
    if let Some(pos) = content.find(&dep_key) {
        if let Some(bracket_pos) = content[pos..].find('[') {
            let insert_at = pos + bracket_pos + 1;
            let new_entry = format!("\"{}\"", package);
            // Check if already present
            if content.contains(&new_entry) { return Ok(()); }
            let mut new_content = content.clone();
            new_content.insert_str(insert_at, &format!("{}, ", new_entry));
            fs::write(manifest_path, &new_content)
                .map_err(|e| format!("Cannot write gx.json: {}", e))?;
        }
    }
    Ok(())
}
